apiVersion: v1
kind: Secret
metadata:
  name: new-custom-config
  namespace: demo
stringData:
  server.properties: |
    process.roles=skipped
    log.retention.hours=99
    log.dirs=/var/new-custom/config
    metadata.log.dir=/var/new-custom/config/metadata