apiVersion: v1
kind: Secret
metadata:
  name: custom-config
  namespace: demo
stringData:
  server.properties: |
    process.roles=skipped
    log.retention.hours=111
    log.dirs=/var/custom/config
    metadata.log.dir=/var/custom/config/metadata