apiVersion: ops.kubedb.com/v1alpha1
kind: KafkaOpsRequest
metadata:
  name: vertical-scaling 
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: kafka-dev
  verticalScaling:
    node:
      limits:
        cpu: 1000m
        memory: 1250Mi
      requests:
        cpu: 502m
        memory: 1100Mi