apiVersion: v1
kind: Secret
metadata:
  name: custom-config
  namespace: demo
stringData:
  broker.properties: |
    log.retention.hours=99
    log.dirs=/var/custom/config
    metadata.log.dir=/var/custom/config/metadata
  controller.properties: |
    log.dirs=/var/custom/config
    metadata.log.dir=/var/custom/config/metadata
  extra.properties: |
    This=is
    extra=config